(load "src/builtins.scm")
(load "src/desugar.scm")
(load "src/multitask.scm")

(define (compile-statement statement)
  (transform-statement (rewrite statement)))
(define (read-and-compile input-port)
  (let ((expr (read input-port)))
    (if (not (eof-object? expr))
        (begin (if (and (pair? expr) (eq? (car expr) 'load))
                   (call-with-input-file (cadr expr) read-and-compile)
                   (write (compile-statement expr)))
               (newline)
               (read-and-compile input-port)))))
(define (compile input-port)
  (begin (for-each (lambda (statement)
                     (begin (write statement)
                            (newline)))
		   (if overload-primitives?
		       (append primitives
			       multitasking-definitions)
		       multitasking-definitions))
         (for-each (lambda (statement)
                     (begin (write (compile-statement statement))
                            (newline)))
                   builtins)
         (read-and-compile input-port)
         (exit)))
(compile (current-input-port))
